import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { hashPassword, passwordProblem, verifyPassword } from "../lib/server/auth/password";
import { safeEqual, sha256Hex } from "../lib/server/auth/tokens";
import { autoGeneratedReason, extractMessageIds, stripQuotedText } from "../lib/server/email/inbound";
import { escapeHtml, htmlToText, isEmptyHtml, sanitizeEmailHtml } from "../lib/server/email/html";
import { fillTemplate } from "../lib/server/email/templates";
import { csvCell, toCsv } from "../lib/server/enquiries/export";
import { formatReference } from "../lib/server/enquiries/reference";
import { resolveRange } from "../lib/server/time";
import { sanitizeFilename, validateUpload } from "../lib/server/uploads/validate";

const pdf = Buffer.from("%PDF-1.4\n1 0 obj\n<<>>\nendobj\ntrailer\n<<>>\n%%EOF\n");
const png = Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), Buffer.alloc(32, 1)]);

/** Minimal ZIP with one stored entry (enough for the central-directory parser). */
function zipWith(name: string): Buffer {
  const filename = Buffer.from(name);
  const local = Buffer.alloc(30 + filename.length);
  local.writeUInt32LE(0x04034b50, 0);
  local.writeUInt16LE(filename.length, 26);
  filename.copy(local, 30);
  const central = Buffer.alloc(46 + filename.length);
  central.writeUInt32LE(0x02014b50, 0);
  central.writeUInt16LE(filename.length, 28);
  central.writeUInt32LE(0, 42);
  filename.copy(central, 46);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(1, 8);
  eocd.writeUInt16LE(1, 10);
  eocd.writeUInt32LE(central.length, 12);
  eocd.writeUInt32LE(local.length, 16);
  return Buffer.concat([local, central, eocd]);
}

describe("passwords", () => {
  it("hashes and verifies, rejecting wrong passwords", async () => {
    const hash = await hashPassword("correct horse battery 9");
    assert.ok(hash.startsWith("scrypt$"));
    assert.equal(await verifyPassword("correct horse battery 9", hash), true);
    assert.equal(await verifyPassword("correct horse battery 8", hash), false);
    assert.equal(await verifyPassword("anything", "not-a-hash"), false);
  });

  it("enforces the password policy", () => {
    assert.match(passwordProblem("short1") ?? "", /12 characters/);
    assert.match(passwordProblem("onlylettersnodigits") ?? "", /letters and numbers/);
    assert.match(passwordProblem("admin-secret-1234", "admin@example.com") ?? "", /email name/);
    assert.equal(passwordProblem("a-solid-passphrase-42", "owner@example.com"), null);
  });

  it("compares tokens in constant time and never stores them raw", () => {
    assert.equal(safeEqual("abc", "abc"), true);
    assert.equal(safeEqual("abc", "abd"), false);
    assert.equal(safeEqual("abc", "abcd"), false);
    assert.equal(sha256Hex("token").length, 64);
  });
});

describe("upload validation", () => {
  it("accepts genuine files", () => {
    const result = validateUpload({ name: "drawing.pdf", data: pdf, declaredType: "application/pdf" });
    assert.equal(result.ok, true);
    assert.equal(validateUpload({ name: "photo.png", data: png }).ok, true);
  });

  it("rejects executables and scripts by extension, including double extensions", () => {
    for (const name of ["setup.exe", "run.bat", "x.cmd", "a.js", "shell.php", "deploy.sh", "invoice.pdf.exe", "page.html", "logo.svg", "shell.php.pdf"]) {
      assert.equal(validateUpload({ name, data: pdf }).ok, false, name);
    }
  });

  it("does not trust the extension: content must match", () => {
    assert.equal(validateUpload({ name: "fake.pdf", data: Buffer.from("MZ\x90\x00 not really a pdf") }).ok, false);
    assert.equal(validateUpload({ name: "fake.pdf", data: Buffer.from("just text") }).ok, false);
    assert.equal(validateUpload({ name: "fake.png", data: pdf }).ok, false);
    assert.equal(validateUpload({ name: "script.pdf", data: Buffer.from("#!/bin/sh\nrm -rf /") }).ok, false);
    assert.equal(validateUpload({ name: "x.pdf", data: pdf, declaredType: "application/x-msdownload" }).ok, false);
  });

  it("rejects archives that contain dangerous files and empty or oversized uploads", () => {
    assert.equal(validateUpload({ name: "ok.zip", data: zipWith("drawing.dwg") }).ok, true);
    assert.equal(validateUpload({ name: "bad.zip", data: zipWith("payload.exe") }).ok, false);
    assert.equal(validateUpload({ name: "bad.zip", data: zipWith("dir/run.bat") }).ok, false);
    assert.equal(validateUpload({ name: "empty.pdf", data: Buffer.alloc(0) }).ok, false);
    assert.equal(validateUpload({ name: "big.pdf", data: Buffer.concat([pdf, Buffer.alloc(2048)]) }, { maxBytes: 1024 }).ok, false);
  });

  it("neutralises path traversal in filenames", () => {
    for (const name of ["../../etc/passwd.pdf", "..\\..\\windows\\system32\\x.pdf", "/abs/path/file.pdf", "a/b/c.pdf"]) {
      const cleaned = sanitizeFilename(name);
      assert.ok(!cleaned.safe.includes("/") && !cleaned.safe.includes("\\") && !cleaned.safe.includes(".."), `${name} -> ${cleaned.safe}`);
    }
    assert.equal(sanitizeFilename("../../x.pdf").display, "x.pdf");
  });
});

describe("html sanitising and templates", () => {
  it("removes scripts, handlers and unsafe URLs", () => {
    const dirty = '<p onclick="x()">Hi</p><script>alert(1)</script><a href="javascript:alert(1)">bad</a><img src=x onerror=alert(1)><iframe src="//evil"></iframe><a href="https://ok.example">ok</a>';
    const clean = sanitizeEmailHtml(dirty);
    assert.ok(!/script|onclick|onerror|javascript:|iframe|<img/i.test(clean), clean);
    assert.ok(clean.includes('href="https://ok.example"'));
    assert.ok(clean.includes('rel="noopener noreferrer"'));
  });

  it("escapes template values and blocks header injection in subjects", () => {
    const html = fillTemplate("<p>Hi {{name}}</p>", { name: '<img src=x onerror=alert(1)>' }, "html");
    assert.ok(!html.includes("<img"));
    const subject = fillTemplate("Re: {{name}}", { name: "A\r\nBcc: attacker@example.com" }, "text");
    assert.ok(!/[\r\n]/.test(subject));
  });

  it("converts html to text and detects empty bodies", () => {
    assert.equal(htmlToText("<p>Hello<br>World</p><p>Bye</p>"), "Hello\nWorld\nBye");
    assert.equal(isEmptyHtml("<p><br></p>"), true);
    assert.equal(isEmptyHtml("<p>x</p>"), false);
    assert.equal(escapeHtml(`<a href="x">&'`), "&lt;a href=&quot;x&quot;&gt;&amp;&#39;");
  });
});

describe("csv export", () => {
  it("quotes commas, quotes and newlines", () => {
    assert.equal(csvCell('a,"b"\nc'), '"a,""b""\nc"');
    assert.equal(csvCell(null), "");
    assert.equal(csvCell(42), "42");
  });

  it("neutralises spreadsheet formula injection", () => {
    for (const value of ["=HYPERLINK(\"http://evil\")", "+1+1", "-2+3", "@SUM(A1)", "\tcmd"]) {
      assert.ok(csvCell(value).replace(/^"/, "").startsWith("'"), value);
    }
    assert.equal(csvCell("normal text"), "normal text");
  });

  it("adds a BOM and CRLF row separators", () => {
    const csv = toCsv(["a", "b"], [["1", "2"]]);
    assert.ok(csv.startsWith("﻿a,b\r\n1,2\r\n"));
  });
});

describe("reference numbers and date ranges", () => {
  it("formats references as RCH-YYYY-NNNNNN", () => {
    assert.equal(formatReference(2026, 124), "RCH-2026-000124");
    assert.equal(formatReference(2027, 1), "RCH-2027-000001");
  });

  it("resolves date presets in the admin timezone", () => {
    const now = new Date("2026-03-15T10:00:00Z");
    const today = resolveRange("today", undefined, undefined, now);
    assert.equal(today.to!.getTime() - today.from!.getTime(), 86_400_000);
    const last7 = resolveRange("last7", undefined, undefined, now);
    assert.equal(last7.to!.getTime() - last7.from!.getTime(), 7 * 86_400_000);
    const custom = resolveRange("custom", "2026-03-01", "2026-03-03", now);
    assert.equal(custom.to!.getTime() - custom.from!.getTime(), 3 * 86_400_000);
    assert.equal(resolveRange("custom", undefined, undefined, now).preset, "all");
  });
});

describe("inbound email helpers", () => {
  it("extracts Message-IDs in order", () => {
    assert.deepEqual(extractMessageIds("<a@x.com> <b@y.com>\n <c@z.com>"), ["<a@x.com>", "<b@y.com>", "<c@z.com>"]);
    assert.deepEqual(extractMessageIds(undefined), []);
  });

  it("detects automatic mail so it is never turned into enquiries", () => {
    const base = { headers: {}, fromEmail: "person@example.com", subject: "Hello" };
    assert.equal(autoGeneratedReason(base), null);
    assert.equal(autoGeneratedReason({ ...base, headers: { "auto-submitted": "auto-replied" } }), "auto-submitted");
    assert.equal(autoGeneratedReason({ ...base, headers: { "auto-submitted": "no" } }), null);
    assert.equal(autoGeneratedReason({ ...base, headers: { precedence: "bulk" } }), "precedence");
    assert.equal(autoGeneratedReason({ ...base, headers: { "list-id": "<x.example.com>" } }), "mailing list");
    assert.equal(autoGeneratedReason({ ...base, fromEmail: "MAILER-DAEMON@mail.example.com" }), "bounce");
    assert.equal(autoGeneratedReason({ ...base, subject: "Out of office: back Monday" }), "auto-reply subject");
  });

  it("keeps only the new part of a reply", () => {
    const reply = "Yes, the deadline is fine.\n\nOn Mon, 3 Mar 2026 at 10:00, Render CAD Hub <support@rendercadhub.com> wrote:\n> Could you confirm the deadline?\n> Thanks";
    assert.equal(stripQuotedText(reply), "Yes, the deadline is fine.");
    assert.equal(stripQuotedText("Plain message\nsecond line"), "Plain message\nsecond line");
    assert.equal(stripQuotedText("> only quoted"), "> only quoted");
  });
});
