import { and, eq, inArray, isNotNull } from "drizzle-orm";
import { emailLogs, enquiries, getDb, messages, type EnquiryStatus } from "../db";
import { logActivity } from "../enquiries/activity";
import { normalizeEmail } from "../enquiries/customers";
import { createEnquiry } from "../enquiries/create";
import { createNotification } from "../enquiries/notifications";
import { REFERENCE_PATTERN } from "../enquiries/reference";
import { refreshThreadCounters } from "../enquiries/thread";
import { hitRateLimit } from "../auth/rate-limit";
import { env } from "../env";
import { errorMessage, log } from "../log";
import { getMailConfig } from "../settings";
import { saveAttachment } from "../uploads/attachments";
import { validateUpload, type ValidatedFile } from "../uploads/validate";
import { sendAdminNotification } from "./send";
import { htmlToText, sanitizeInboundHtml, singleLine, textToHtml } from "./html";

export type InboundAttachment = { filename: string; contentType: string; content: Buffer };

export type InboundEmail = {
  messageId: string | null;
  inReplyTo: string | null;
  /** Message-IDs from the References header, oldest first. */
  references: string[];
  fromEmail: string;
  fromName: string;
  to: string[];
  cc: string[];
  subject: string;
  text: string;
  html: string | null;
  date: Date | null;
  attachments: InboundAttachment[];
  /** Lower-cased header name → value; only the ones used for auto-reply detection are needed. */
  headers: Record<string, string>;
};

export type IngestResult =
  | { outcome: "matched"; enquiryId: string; referenceNumber: string; messageRowId: string; attachmentsSaved: number }
  | { outcome: "created"; enquiryId: string; referenceNumber: string; messageRowId: string | null; attachmentsSaved: number }
  | { outcome: "duplicate" }
  | { outcome: "ignored"; reason: string };

const MAX_TEXT_CHARS = 100_000;
const MAX_ATTACHMENTS = 10;
const MAX_TOTAL_ATTACHMENT_BYTES = 40 * 1024 * 1024;
const NEW_ENQUIRIES_PER_HOUR = 100;

/** Statuses a customer reply re-opens. Everything else keeps its status and is only flagged unread. */
const REOPEN_TO_IN_REVIEW: readonly EnquiryStatus[] = ["AWAITING_CUSTOMER", "CLOSED", "LOST"];

// ---------------------------------------------------------------------------
// Detection helpers
// ---------------------------------------------------------------------------

export function extractMessageIds(value: string | null | undefined): string[] {
  if (!value) return [];
  return Array.from(value.matchAll(/<[^<>\s]+>/g), (m) => m[0]);
}

/** Auto-replies, bounces, mailing lists — never create or extend enquiries from these. */
export function autoGeneratedReason(mail: Pick<InboundEmail, "headers" | "fromEmail" | "subject">): string | null {
  const h = mail.headers;
  const autoSubmitted = h["auto-submitted"]?.toLowerCase().trim();
  if (autoSubmitted && autoSubmitted !== "no") return "auto-submitted";
  if (/^(bulk|junk|list|auto_reply)$/i.test(h["precedence"]?.trim() ?? "")) return "precedence";
  if (h["x-autoreply"] || h["x-autorespond"] || h["x-auto-response-suppress"]) return "auto-reply header";
  if (h["list-id"] || h["list-unsubscribe"]) return "mailing list";
  if (/^(mailer-daemon|postmaster)@/i.test(mail.fromEmail)) return "bounce";
  if (/^(auto(matic)? ?reply|out of office|undeliverable|delivery status notification|mail delivery)/i.test(mail.subject.trim())) return "auto-reply subject";
  return null;
}

/** Removes the quoted history so only what the customer just wrote is stored as the reply. */
export function stripQuotedText(text: string): string {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  const cut = lines.findIndex((line, index) => {
    const trimmed = line.trim();
    if (/^on .{5,200}wrote:?$/i.test(trimmed)) return true;
    if (/^-{2,}\s*(original message|forwarded message)\s*-{2,}$/i.test(trimmed)) return true;
    if (/^_{5,}$/.test(trimmed) && /^(from|sent):/i.test(lines[index + 1]?.trim() ?? "")) return true;
    if (/^from:\s.+/i.test(trimmed) && /^(sent|date):\s/i.test(lines[index + 1]?.trim() ?? "") && index > 0) return true;
    return false;
  });
  const kept = (cut === -1 ? lines : lines.slice(0, cut)).filter((line, index, all) => !(line.startsWith(">") && all.slice(index).every((rest) => rest.startsWith(">") || rest.trim() === "")));
  const result = kept.join("\n").trim();
  return result || text.trim();
}

// ---------------------------------------------------------------------------
// Matching
// ---------------------------------------------------------------------------

async function findEnquiryFor(mail: InboundEmail) {
  const db = await getDb();
  const ids = [...new Set([...(mail.inReplyTo ? [mail.inReplyTo] : []), ...mail.references])].slice(-25);

  if (ids.length) {
    // Message-IDs are unguessable (UUIDs), so a header match is trusted regardless of the sender address.
    const viaMessages = await db
      .select({ enquiryId: messages.enquiryId })
      .from(messages)
      .where(inArray(messages.messageId, ids))
      .limit(1);
    if (viaMessages[0]) return viaMessages[0].enquiryId;
    // Confirmation / notification emails are logged but not stored as messages.
    const viaLogs = await db
      .select({ enquiryId: emailLogs.enquiryId })
      .from(emailLogs)
      .where(and(inArray(emailLogs.messageId, ids), isNotNull(emailLogs.enquiryId)))
      .limit(1);
    if (viaLogs[0]?.enquiryId) return viaLogs[0].enquiryId;
  }

  // Fallback: reference number in the subject. Guessable, so the sender must be the enquiry's own customer.
  const reference = REFERENCE_PATTERN.exec(mail.subject)?.[0]?.toUpperCase();
  if (reference) {
    const [row] = await db
      .select({ id: enquiries.id })
      .from(enquiries)
      .where(and(eq(enquiries.referenceNumber, reference), eq(enquiries.email, normalizeEmail(mail.fromEmail))))
      .limit(1);
    if (row) return row.id;
  }
  return null;
}

async function validateInboundFiles(mail: InboundEmail): Promise<{ files: ValidatedFile[]; rejected: string[] }> {
  const files: ValidatedFile[] = [];
  const rejected: string[] = [];
  let total = 0;
  for (const item of mail.attachments.slice(0, MAX_ATTACHMENTS)) {
    total += item.content.length;
    if (total > MAX_TOTAL_ATTACHMENT_BYTES) {
      rejected.push(`${item.filename}: total attachment size limit reached`);
      continue;
    }
    const result = validateUpload({ name: item.filename || "attachment", data: item.content, declaredType: item.contentType }, { maxBytes: env.maxInternalFileBytes });
    if (result.ok) files.push(result.file);
    else rejected.push(`${item.filename || "attachment"}: ${result.reason}`);
  }
  for (const extra of mail.attachments.slice(MAX_ATTACHMENTS)) rejected.push(`${extra.filename}: too many attachments`);
  return { files, rejected };
}

// ---------------------------------------------------------------------------
// Ingest
// ---------------------------------------------------------------------------

export async function ingestInboundEmail(mail: InboundEmail): Promise<IngestResult> {
  const db = await getDb();
  const config = await getMailConfig();
  const from = normalizeEmail(mail.fromEmail);
  if (!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(from)) return { outcome: "ignored", reason: "invalid sender address" };

  // Loop guard: never ingest mail that we sent ourselves.
  const ours = new Set([config.businessEmail, config.fromEmail, config.smtp.user ?? ""].map((v) => v.toLowerCase()).filter(Boolean));
  if (ours.has(from)) return { outcome: "ignored", reason: "sent by this mailbox" };

  const messageId = mail.messageId ? singleLine(mail.messageId).slice(0, 500) : null;
  if (messageId) {
    const [known] = await db.select({ id: messages.id }).from(messages).where(eq(messages.messageId, messageId)).limit(1);
    if (known) return { outcome: "duplicate" };
  }

  const auto = autoGeneratedReason({ headers: mail.headers, fromEmail: from, subject: mail.subject });
  if (auto) {
    if (auto === "bounce") await recordBounce(mail);
    return { outcome: "ignored", reason: auto };
  }

  const rawText = (mail.text || (mail.html ? htmlToText(mail.html) : "")).slice(0, MAX_TEXT_CHARS);
  if (!rawText.trim() && mail.attachments.length === 0) return { outcome: "ignored", reason: "empty message" };

  const { files, rejected } = await validateInboundFiles(mail);
  const enquiryId = await findEnquiryFor(mail);
  const receivedAt = mail.date && Math.abs(mail.date.getTime() - Date.now()) < 3 * 365 * 86_400_000 ? mail.date : new Date();
  const subject = singleLine(mail.subject || "(no subject)").slice(0, 300);

  if (enquiryId) return appendReply({ enquiryId, mail, from, subject, rawText, receivedAt, files, rejected, messageId });
  return createFromEmail({ mail, from, subject, rawText, receivedAt, files, rejected, messageId });
}

async function appendReply(args: {
  enquiryId: string;
  mail: InboundEmail;
  from: string;
  subject: string;
  rawText: string;
  receivedAt: Date;
  files: ValidatedFile[];
  rejected: string[];
  messageId: string | null;
}): Promise<IngestResult> {
  const db = await getDb();
  const { mail, from, subject, receivedAt, files, rejected, messageId } = args;
  const bodyText = stripQuotedText(args.rawText).slice(0, MAX_TEXT_CHARS);
  const cleanedHtml = mail.html ? sanitizeInboundHtml(mail.html) : "";
  const bodyHtml = cleanedHtml && htmlToText(cleanedHtml).trim() ? cleanedHtml : textToHtml(bodyText || "(no text — see attachments)");

  const outcome = await db.transaction(async (tx) => {
    const [enquiry] = await tx.select().from(enquiries).where(eq(enquiries.id, args.enquiryId)).for("update");
    if (!enquiry) return null;

    const [message] = await tx
      .insert(messages)
      .values({
        enquiryId: enquiry.id,
        direction: "INBOUND",
        senderName: mail.fromName || null,
        senderEmail: from,
        recipientEmail: mail.to[0] ?? enquiry.email,
        cc: mail.cc.length ? mail.cc.join(", ").slice(0, 1000) : null,
        subject,
        bodyHtml,
        bodyText: bodyText || "(no text — see attachments)",
        messageId,
        inReplyTo: mail.inReplyTo,
        messageReferences: mail.references.join(" ") || null,
        status: "RECEIVED",
        receivedAt,
      })
      .onConflictDoNothing()
      .returning({ id: messages.id });
    if (!message) return null; // lost a race with the same Message-ID

    for (const file of files) await saveAttachment(tx, { enquiryId: enquiry.id, messageId: message.id, uploadedBy: "CUSTOMER" }, file);

    const reopen = REOPEN_TO_IN_REVIEW.includes(enquiry.status);
    const resurfaced = Boolean(enquiry.archivedAt || enquiry.deletedAt);
    await refreshThreadCounters(tx, enquiry.id);
    await tx
      .update(enquiries)
      .set({
        isRead: false,
        lastCustomerReplyAt: receivedAt,
        ...(reopen ? { status: "IN_REVIEW" as const, closedAt: null } : {}),
        ...(resurfaced ? { archivedAt: null, deletedAt: null } : {}),
      })
      .where(eq(enquiries.id, enquiry.id));

    await logActivity(tx, {
      enquiryId: enquiry.id,
      referenceNumber: enquiry.referenceNumber,
      action: "CUSTOMER_REPLY_RECEIVED",
      description: `Customer replied by email${files.length ? ` with ${files.length} attachment${files.length === 1 ? "" : "s"}` : ""}`,
      actor: "CUSTOMER",
      metadata: { from },
    });
    if (reopen) {
      await logActivity(tx, {
        enquiryId: enquiry.id,
        referenceNumber: enquiry.referenceNumber,
        action: "STATUS_CHANGED",
        description: `Status changed to In Review because the customer replied (was ${enquiry.status})`,
        actor: "SYSTEM",
        metadata: { from: enquiry.status, to: "IN_REVIEW" },
      });
    }
    if (resurfaced) {
      await logActivity(tx, {
        enquiryId: enquiry.id,
        referenceNumber: enquiry.referenceNumber,
        action: "ENQUIRY_RESTORED",
        description: "Restored automatically because the customer replied",
        actor: "SYSTEM",
      });
    }
    if (rejected.length) {
      await logActivity(tx, {
        enquiryId: enquiry.id,
        referenceNumber: enquiry.referenceNumber,
        action: "ATTACHMENT_REJECTED",
        description: `Attachments not saved — ${rejected.join("; ").slice(0, 400)}`,
        actor: "SYSTEM",
      });
    }
    await createNotification(tx, {
      type: "CUSTOMER_REPLIED",
      title: `Customer replied — ${enquiry.referenceNumber}`,
      body: enquiry.name,
      enquiryId: enquiry.id,
      referenceNumber: enquiry.referenceNumber,
      dedupeKey: `reply:${message.id}`,
    });
    return { enquiryId: enquiry.id, referenceNumber: enquiry.referenceNumber, messageRowId: message.id };
  });

  if (!outcome) return { outcome: "duplicate" };
  log.info("inbound.matched", { reference: outcome.referenceNumber, files: files.length, rejected: rejected.length });
  return { outcome: "matched", ...outcome, attachmentsSaved: files.length };
}

async function createFromEmail(args: {
  mail: InboundEmail;
  from: string;
  subject: string;
  rawText: string;
  receivedAt: Date;
  files: ValidatedFile[];
  rejected: string[];
  messageId: string | null;
}): Promise<IngestResult> {
  const db = await getDb();
  const { mail, from, subject, receivedAt, files, rejected, messageId } = args;

  // A flood of unrelated mail must not be able to create unlimited enquiries.
  const limit = await hitRateLimit("inbound:new-enquiries", NEW_ENQUIRIES_PER_HOUR, 3600);
  if (!limit.allowed) {
    log.warn("inbound.rate_limited", { from: from.split("@")[1] });
    return { outcome: "ignored", reason: "too many new enquiries from email this hour" };
  }

  const bodyText = stripQuotedText(args.rawText).slice(0, MAX_TEXT_CHARS);
  const cleanedHtml = mail.html ? sanitizeInboundHtml(mail.html) : "";
  const bodyHtml = cleanedHtml && htmlToText(cleanedHtml).trim() ? cleanedHtml : textToHtml(bodyText || "(no text — see attachments)");
  const name = mail.fromName.trim().slice(0, 120) || from.split("@")[0];

  const created = await createEnquiry({
    type: "CONTACT_MESSAGE",
    source: "DIRECT",
    name,
    email: from,
    description: bodyText || "(no text — see attachments)",
    files,
    firstMessage: {
      subject,
      bodyText: bodyText || "(no text — see attachments)",
      bodyHtml,
      messageId,
      inReplyTo: mail.inReplyTo,
      messageReferences: mail.references.join(" ") || null,
      receivedAt,
    },
  });
  if (created.duplicate) return { outcome: "duplicate" };

  if (rejected.length) {
    await logActivity(db, {
      enquiryId: created.id,
      referenceNumber: created.referenceNumber,
      action: "ATTACHMENT_REJECTED",
      description: `Attachments not saved — ${rejected.join("; ").slice(0, 400)}`,
      actor: "SYSTEM",
    });
  }
  const [message] = await db.select({ id: messages.id }).from(messages).where(eq(messages.enquiryId, created.id)).limit(1);
  // The admin is notified; no automatic confirmation is sent to a sender who never used the form.
  try {
    await sendAdminNotification(created.id);
  } catch (error) {
    log.error("inbound.notify_failed", { error: errorMessage(error) });
  }
  log.info("inbound.created", { reference: created.referenceNumber, files: files.length });
  return { outcome: "created", enquiryId: created.id, referenceNumber: created.referenceNumber, messageRowId: message?.id ?? null, attachmentsSaved: files.length };
}

/** A bounce that references one of our emails becomes a visible "email failed" alert. */
async function recordBounce(mail: InboundEmail) {
  const db = await getDb();
  const ids = [...new Set([...(mail.inReplyTo ? [mail.inReplyTo] : []), ...mail.references])].slice(-25);
  if (!ids.length) return;
  const [logRow] = await db
    .select({ id: emailLogs.id, enquiryId: emailLogs.enquiryId, recipient: emailLogs.recipient })
    .from(emailLogs)
    .where(and(inArray(emailLogs.messageId, ids), isNotNull(emailLogs.enquiryId)))
    .limit(1);
  if (!logRow?.enquiryId) return;
  const [enquiry] = await db.select({ ref: enquiries.referenceNumber }).from(enquiries).where(eq(enquiries.id, logRow.enquiryId)).limit(1);
  await logActivity(db, {
    enquiryId: logRow.enquiryId,
    referenceNumber: enquiry?.ref,
    action: "EMAIL_FAILED",
    description: `The mail server reported a delivery problem for the email to ${logRow.recipient}`,
    actor: "SYSTEM",
  });
  await createNotification(db, {
    type: "EMAIL_FAILED",
    title: `Delivery problem — ${enquiry?.ref ?? "enquiry"}`,
    body: `Email to ${logRow.recipient} bounced`,
    enquiryId: logRow.enquiryId,
    referenceNumber: enquiry?.ref,
    dedupeKey: `bounce:${logRow.id}`,
  });
}
