import { randomUUID } from "node:crypto";
import { and, eq, inArray, lt, or, sql } from "drizzle-orm";
import { SITE } from "@/lib/constants";
import { attachments, emailLogs, enquiries, getDb, messages, type DbOrTx, type EmailPayload, type EmailStatus } from "../db";
import { logActivity } from "../enquiries/activity";
import { createNotification } from "../enquiries/notifications";
import { applyOutboundSent } from "../enquiries/thread";
import { log } from "../log";
import { getMailConfig, type MailConfig } from "../settings";
import { attachmentsByIds, getAttachmentWithData } from "../uploads/attachments";
import { emailLayout, htmlToText, escapeHtml, singleLine } from "./html";
import { formatAddress, safeError, sendRaw } from "./mailer";
import { fillTemplate, getTemplate, type TemplateKey } from "./templates";

/** Templates generated by the system; these carry an Auto-Submitted header so autoresponders don't loop. */
const AUTOMATIC_TEMPLATES = new Set(["quote_received", "contact_received", "admin_new_enquiry", "admin_new_contact", "password_reset", "smtp_test"]);

export type QueueEmailInput = {
  to: string;
  cc?: string | null;
  bcc?: string | null;
  subject: string;
  html: string;
  text: string;
  template?: string;
  enquiryId?: string | null;
  messageRowId?: string | null;
  replyTo?: string;
  inReplyTo?: string;
  references?: string;
  attachmentIds?: string[];
  statusAfter?: string;
  messageId?: string;
  /** Set false for emails that must never be stored/replayed (password reset links). */
  storePayload?: boolean;
};

export type DeliveryResult = { status: EmailStatus; error?: string; logId: string };

export function makeMessageId(config: MailConfig): string {
  const domain = config.fromEmail.split("@")[1] ?? "localhost";
  return `<${randomUUID()}@${domain}>`;
}

export async function queueEmail(db: DbOrTx, input: QueueEmailInput, config: MailConfig): Promise<{ id: string; messageId: string }> {
  const messageId = input.messageId ?? makeMessageId(config);
  const payload: EmailPayload | null =
    input.storePayload === false
      ? null
      : {
          html: input.html,
          text: input.text,
          replyTo: input.replyTo,
          inReplyTo: input.inReplyTo,
          references: input.references,
          attachmentIds: input.attachmentIds,
          statusAfter: input.statusAfter,
        };
  const [row] = await db
    .insert(emailLogs)
    .values({
      enquiryId: input.enquiryId ?? null,
      messageRowId: input.messageRowId ?? null,
      recipient: singleLine(input.to).slice(0, 500),
      cc: input.cc ? singleLine(input.cc).slice(0, 500) : null,
      bcc: input.bcc ? singleLine(input.bcc).slice(0, 500) : null,
      sender: config.fromEmail,
      subject: singleLine(input.subject).slice(0, 300),
      template: input.template ?? null,
      messageId,
      status: "QUEUED",
      payload,
    })
    .returning({ id: emailLogs.id });
  return { id: row.id, messageId };
}

/**
 * Sends one queued email. Atomically claims the row first so a double click
 * on "Retry" can never send the same message twice.
 */
export async function deliverEmail(logId: string, transient?: EmailPayload): Promise<DeliveryResult> {
  const db = await getDb();
  const config = await getMailConfig();
  const staleBefore = new Date(Date.now() - 5 * 60_000);

  const [claimed] = await db
    .update(emailLogs)
    .set({ status: "SENDING", attemptCount: sql`${emailLogs.attemptCount} + 1`, lastAttemptAt: new Date() })
    .where(
      and(
        eq(emailLogs.id, logId),
        or(inArray(emailLogs.status, ["QUEUED", "FAILED"]), and(eq(emailLogs.status, "SENDING"), lt(emailLogs.lastAttemptAt, staleBefore))),
      ),
    )
    .returning();

  if (!claimed) {
    const [current] = await db.select({ status: emailLogs.status }).from(emailLogs).where(eq(emailLogs.id, logId)).limit(1);
    return { status: current?.status ?? "FAILED", logId, error: current ? undefined : "Email log not found." };
  }

  const fail = async (message: string): Promise<DeliveryResult> => {
    await db.update(emailLogs).set({ status: "FAILED", errorMessage: message }).where(eq(emailLogs.id, logId));
    if (claimed.messageRowId) await db.update(messages).set({ status: "FAILED" }).where(eq(messages.id, claimed.messageRowId));
    log.error("email.send_failed", { logId, template: claimed.template, attempt: claimed.attemptCount, error: message });
    if (claimed.enquiryId && claimed.template !== "smtp_test") {
      const [enquiry] = await db.select({ ref: enquiries.referenceNumber }).from(enquiries).where(eq(enquiries.id, claimed.enquiryId)).limit(1);
      await logActivity(db, {
        enquiryId: claimed.enquiryId,
        referenceNumber: enquiry?.ref,
        action: claimed.attemptCount > 1 ? "EMAIL_RETRIED" : "EMAIL_FAILED",
        description: `${claimed.attemptCount > 1 ? "Email retry failed" : "Email failed"}: “${claimed.subject}” to ${claimed.recipient} — ${message}`,
        actor: "SYSTEM",
        metadata: { logId },
      });
      if (config.notify.emailFailure) {
        await createNotification(db, {
          type: "EMAIL_FAILED",
          title: `Email failed for ${enquiry?.ref ?? "enquiry"}`,
          body: `“${claimed.subject}” to ${claimed.recipient}`,
          enquiryId: claimed.enquiryId,
          referenceNumber: enquiry?.ref,
          dedupeKey: `emailfail:${logId}:${claimed.attemptCount}`,
        });
      }
    }
    return { status: "FAILED", error: message, logId };
  };

  const payload = claimed.payload ?? transient;
  if (!payload) return fail("This email can no longer be sent because its content was intentionally not stored.");
  if (!config.smtp.configured) return fail("SMTP is not configured. Add your mail server details in Settings → SMTP.");

  try {
    const stored = await attachmentsByIds(payload.attachmentIds ?? []);
    const files = [];
    for (const meta of stored) {
      const found = await getAttachmentWithData(meta.id);
      if (found) files.push({ filename: meta.originalFilename, content: found.data, contentType: meta.mimeType });
    }

    const info = await sendRaw(config, {
      from: formatAddress(config.fromName, config.fromEmail),
      to: claimed.recipient,
      cc: claimed.cc ?? undefined,
      bcc: claimed.bcc ?? undefined,
      replyTo: payload.replyTo ?? config.businessEmail,
      subject: claimed.subject,
      html: payload.html,
      text: payload.text,
      messageId: claimed.messageId ?? undefined,
      inReplyTo: payload.inReplyTo,
      references: payload.references,
      attachments: files,
      headers: claimed.template && AUTOMATIC_TEMPLATES.has(claimed.template) ? { "Auto-Submitted": "auto-generated" } : undefined,
    });

    const now = new Date();
    await db
      .update(emailLogs)
      .set({ status: "SENT", sentAt: now, providerResponse: String(info.response ?? "").slice(0, 300), errorMessage: null })
      .where(eq(emailLogs.id, logId));
    if (claimed.messageRowId) {
      await db.update(messages).set({ status: "SENT", sentAt: now }).where(eq(messages.id, claimed.messageRowId));
      const [sent] = await db.select({ direction: messages.direction }).from(messages).where(eq(messages.id, claimed.messageRowId)).limit(1);
      if (sent?.direction === "OUTBOUND" && claimed.enquiryId) await applyOutboundSent(claimed.enquiryId, claimed.recipient, payload.statusAfter);
    }
    if (claimed.attemptCount > 1 && claimed.enquiryId) {
      await logActivity(db, {
        enquiryId: claimed.enquiryId,
        action: "EMAIL_RETRIED",
        description: `Email retry succeeded: “${claimed.subject}” to ${claimed.recipient}`,
        actor: "SYSTEM",
        metadata: { logId },
      });
    }
    log.info("email.sent", { logId, template: claimed.template, attempt: claimed.attemptCount });
    return { status: "SENT", logId };
  } catch (error) {
    return fail(safeError(error, config));
  }
}

export async function sendEmail(input: QueueEmailInput): Promise<DeliveryResult> {
  const db = await getDb();
  const config = await getMailConfig();
  const { id } = await queueEmail(db, input, config);
  return deliverEmail(id, input.storePayload === false ? { html: input.html, text: input.text, replyTo: input.replyTo } : undefined);
}

export async function retryEmail(logId: string): Promise<DeliveryResult> {
  return deliverEmail(logId);
}

// ---------------------------------------------------------------------------
// Named senders
// ---------------------------------------------------------------------------

async function loadEnquiry(id: string) {
  const db = await getDb();
  const [row] = await db.select().from(enquiries).where(eq(enquiries.id, id)).limit(1);
  return row ?? null;
}

export async function sendCustomerConfirmation(enquiryId: string): Promise<DeliveryResult | { skipped: true }> {
  const config = await getMailConfig();
  if (!config.notify.customerConfirmation) return { skipped: true };
  const enquiry = await loadEnquiry(enquiryId);
  if (!enquiry) return { skipped: true };

  const key: TemplateKey = enquiry.type === "QUOTE_REQUEST" ? "quote_received" : "contact_received";
  const template = await getTemplate(key);
  const vars = {
    name: enquiry.name,
    reference_number: enquiry.referenceNumber,
    service: enquiry.service ?? "your project",
    support_email: config.businessEmail,
    site_name: SITE.name,
  };
  const bodyHtml = fillTemplate(template.bodyHtml, vars, "html");
  const html = emailLayout({ bodyHtml, siteName: SITE.name, supportEmail: config.businessEmail, footerNote: `Reference ${enquiry.referenceNumber}` });
  const result = await sendEmail({
    to: enquiry.email,
    subject: fillTemplate(template.subject, vars, "text"),
    html,
    text: htmlToText(bodyHtml),
    template: key,
    enquiryId: enquiry.id,
    replyTo: config.businessEmail,
  });
  if (result.status === "SENT") {
    const db = await getDb();
    await logActivity(db, {
      enquiryId: enquiry.id,
      referenceNumber: enquiry.referenceNumber,
      action: "CONFIRMATION_SENT",
      description: `Confirmation email sent to ${enquiry.email}`,
      actor: "SYSTEM",
    });
  }
  return result;
}

export async function sendAdminNotification(enquiryId: string): Promise<DeliveryResult | { skipped: true }> {
  const config = await getMailConfig();
  if (!config.notify.newEnquiry) return { skipped: true };
  const enquiry = await loadEnquiry(enquiryId);
  if (!enquiry) return { skipped: true };

  const isQuote = enquiry.type === "QUOTE_REQUEST";
  const db = await getDb();
  const [{ files }] = await db.select({ files: sql<number>`count(*)::int` }).from(attachments).where(eq(attachments.enquiryId, enquiry.id));

  const rows: [string, string | null | undefined][] = [
    ["Reference", enquiry.referenceNumber],
    ["Type", isQuote ? "Quote request" : "Contact message"],
    ["Name", enquiry.name],
    ["Company", enquiry.company],
    ["Email", enquiry.email],
    ["Phone", enquiry.phone],
    ["Service", enquiry.service],
    ["Project type", enquiry.projectType],
    ["Timeline", enquiry.timeline],
    ["Budget", enquiry.budget],
    ["Location", [enquiry.city, enquiry.country].filter(Boolean).join(", ")],
    ["Source", enquiry.source.replace("_", " ").toLowerCase()],
    ["Landing page", enquiry.landingPage],
    ["Campaign", [enquiry.utmSource, enquiry.utmMedium, enquiry.utmCampaign].filter(Boolean).join(" / ")],
    ["Attachments", files ? `${files} file${files === 1 ? "" : "s"}` : ""],
  ];
  const table = rows
    .filter(([, value]) => value)
    .map(([label, value]) => `<tr><td style="padding:6px 12px 6px 0;color:#6b7280;vertical-align:top;white-space:nowrap;">${escapeHtml(label)}</td><td style="padding:6px 0;">${escapeHtml(String(value))}</td></tr>`)
    .join("");
  const bodyHtml =
    `<table role="presentation" cellspacing="0" cellpadding="0" style="font-size:14px;">${table}</table>` +
    `<p style="margin:20px 0 6px;color:#6b7280;font-size:13px;">${isQuote ? "Project description" : "Message"}</p>` +
    `<div style="border-left:3px solid #c16a2f;padding:4px 0 4px 12px;white-space:pre-wrap;">${escapeHtml(enquiry.projectDescription)}</div>`;
  const html = emailLayout({
    heading: isQuote ? "New quote request" : "New contact message",
    bodyHtml,
    button: { label: "View Enquiry", url: `${SITE.url.replace(/\/$/, "")}/admin/enquiries/${enquiry.id}/` },
    siteName: SITE.name,
    supportEmail: config.businessEmail,
  });
  const text =
    `${isQuote ? "New quote request" : "New contact message"} ${enquiry.referenceNumber}\n\n` +
    rows.filter(([, v]) => v).map(([l, v]) => `${l}: ${v}`).join("\n") +
    `\n\n${enquiry.projectDescription}\n\nView: ${SITE.url.replace(/\/$/, "")}/admin/enquiries/${enquiry.id}/`;

  return sendEmail({
    to: config.businessEmail,
    subject: `${isQuote ? "New Enquiry" : "New Contact Message"} — ${enquiry.referenceNumber}`,
    html,
    text,
    template: isQuote ? "admin_new_enquiry" : "admin_new_contact",
    enquiryId: enquiry.id,
    replyTo: enquiry.email,
  });
}

export async function sendPasswordReset(admin: { email: string; name: string }, link: string): Promise<DeliveryResult> {
  const config = await getMailConfig();
  const template = await getTemplate("password_reset");
  const vars = { name: admin.name, site_name: SITE.name, reset_link: link };
  const bodyHtml = fillTemplate(template.bodyHtml, vars, "html");
  const html = emailLayout({
    bodyHtml,
    button: { label: "Choose a new password", url: link },
    siteName: SITE.name,
    supportEmail: config.businessEmail,
    footerNote: "This link expires in 60 minutes.",
  });
  return sendEmail({
    to: admin.email,
    subject: fillTemplate(template.subject, vars, "text"),
    html,
    text: `${htmlToText(bodyHtml)}\n\n${link}`,
    template: "password_reset",
    storePayload: false,
  });
}

export async function sendTestEmail(to: string): Promise<DeliveryResult> {
  const config = await getMailConfig();
  const bodyHtml = `<p>This is a test email from the ${escapeHtml(SITE.name)} admin.</p><p>If you received it, your SMTP settings are working.</p>`;
  return sendEmail({
    to,
    subject: `${SITE.name} — SMTP test`,
    html: emailLayout({ heading: "SMTP test", bodyHtml, siteName: SITE.name, supportEmail: config.businessEmail }),
    text: htmlToText(bodyHtml),
    template: "smtp_test",
  });
}
